### ISSUE TITLE
Lifebloom Issue Reappear

### ISSUE THREAD

**Issue by SozVCN** [RR2739-VCN/Redrum-PvP#21] opened 2019-05-03 12:08 UTC
**Describe the bug**
Lifebloom healing is greatly flawed, it needs recorrecting. I saw a previous post about it 26 days ago, and it was called fixed 20 days ago, yet the issue seems to have reappeared. I think that it doesn't factor in bonus healing, or if the case it does, the bonus healing scaling on Lifebloom has been thwarted somehow.

**To Reproduce**
The HoT effect ticks for 500 (1 stack), 1000 (2 stacks) and 1500 (3 stacks), the heal at the end of Lifebloom heals for 1800 (1 stack), 2500 (2 stacks) and 3300 (3 stacks).

**Expected behavior**
Truthfully? Decent heals. It is currently worthless.

**Screenshots**
I do not see the need for a screenshot, since it is easily both checked, and somewhat understandable through what I've explained above. 

**Additional context**
Currently, druid healing is gravely flawed, as running a decent PvP build focusing on low amounts of players, which is usually the go-to, is actually affecting you negatively. Lifebloom is a static decent HoT with a big oomph at the end, hence fixing it is rather important.

**Comment by Illuminati2739** [comment] 2019-05-03 14:06
We did fix the tic amounts abd final heal. We did not see any discrepancies. However we are going to test this again to make the issue is corrected once and for all.

**Comment by D-CellX** [comment] 2019-05-03 14:12
According to the fix logs the issue was corrected and fixed. The tics and final effect aura. However we will look in to it again to make sure its fixed once and for all.

**Closed as completed** 2019-08-19 05:14 UTC
Labels: Spells/Abilities
